<?php

namespace Empiriq\BinanceContracts\Derivatives\FuturesUsdM\Common;

enum AccountUpdateReason: string
{
    case DEPOSIT = 'DEPOSIT';
    case WITHDRAW = 'WITHDRAW';
    case ORDER = 'ORDER';
    case FUNDING_FEE = 'FUNDING_FEE';
    case WITHDRAW_REJECT = 'WITHDRAW_REJECT';
    case ADJUSTMENT = 'ADJUSTMENT';
    case INSURANCE_CLEAR = 'INSURANCE_CLEAR';
    case ADMIN_DEPOSIT = 'ADMIN_DEPOSIT';
    case ADMIN_WITHDRAW = 'ADMIN_WITHDRAW';
    case MARGIN_TRANSFER = 'MARGIN_TRANSFER';
    case MARGIN_TYPE_CHANGE = 'MARGIN_TYPE_CHANGE';
    case ASSET_TRANSFER = 'ASSET_TRANSFER';
    case OPTIONS_PREMIUM_FEE = 'OPTIONS_PREMIUM_FEE';
    case OPTIONS_SETTLE_PROFIT = 'OPTIONS_SETTLE_PROFIT';
    case AUTO_EXCHANGE = 'AUTO_EXCHANGE';
    case COIN_SWAP_DEPOSIT = 'COIN_SWAP_DEPOSIT';
    case COIN_SWAP_WITHDRAW = 'COIN_SWAP_WITHDRAW';
}
