binance_api_connector:
    api_key: '%env(default:4bbd70a3c5657b4f574dae1622c4449a7b5893fab147d6d9ec098c8be524f6df:BINANCE_API_KEY)%'
    api_secret: '%env(default:6422295ea0671998ef386c3faf9ab457ee013ae76502d50d48795888189ee831:BINANCE_API_SECRET)%'
    rest_api_uri: 'https://testnet.binancefuture.com'
    websocket_api_uri: 'wss://testnet.binancefuture.com/ws-fapi/v1'
    websocket_market_streams_uri: 'wss://fstream.binancefuture.com/ws'
    resolver_timeout: 15
    symbols: ['BTCUSDT', 'ETHUSDT']
